### ISSUE TITLE
[Proposal] Add dask-gateway to this chart

### ISSUE THREAD

**Issue by jhamman** [pangeo-data/helm-chart#101]
I think we're getting to the place where we can start thinking about how to include dask-gateway in this project. Just to quickly summarize some of the motivation for this proposal:

- Our current daskkubernetes [RBAC](https://github.com/pangeo-data/helm-chart/blob/master/pangeo/templates/dask-kubernetes-rbac.yaml) gives all uses on the hub permissions to `["get", "list", "watch", "create", "delete"]` any pods/services on the cluster. We've long known this is not a long term solution to allowing user to control their dask resources
- We don't have clean ways to limit users usage or resources.

Dask-gateway gives us the ability to solve both of these problems (and a few more). So what is our path toward adoption of the dask-gateway chart? Is it too soon? Is it missing features we think we should wait for? Would this change require us to disable the RBAC solution or is there a use case for keeping both solutions here?

cc @jcrist, @jacobtomlinson, @TomAugspurger, @yuvipanda

**Comment by rabernat** [comment]
I'm admittedly not up on many of the details, but think we should go all in on dask gateway!

**Comment by jcrist** [comment]
I'm finishing up some work making dask-gateway more compatible with the other dask clusters, which should make this change easier on your users. I think you may want to keep the user serviceaccounts around for a bit until things have seen more use, but I'd be happy to get things setup in a way that users could try things out.

My short term plan:
- Finish up some user interface changes (hopefully today/tomorrow).
- Release later this week/early next week.
- Add dask-gateway's helm chart a a subchart to the pangeo chart.

**Comment by jhamman** [comment]
closed via #104
