### ISSUE TITLE
how can i use docker image instead of helm-chart to deploy pangeo?

### ISSUE THREAD

**Issue by xinxinh2020** [pangeo-data/helm-chart#118]
for some reason,i have no a helm environment and not intend to deploy pangeo in public cloud such as GEC. can i use kubernetes with docker image instead of helm-chart to deploy pangeo?

**Comment by jhamman** [comment]
@huangxinxin-szu -

You may checkout the helm documentation on how to install the helm command line tools: https://helm.sh/docs/intro/install/

More broadly though, it would be useful to know what your use case is. I'm inclined to say the most direct way to deploy Pangeo on kubernetes is via this helm chart. You may also be interested in the [pangeo-stacks](https://github.com/pangeo-data/pangeo-stacks) repository of Pangeo-ready docker images.

**Comment by jacobtomlinson** [comment]
It is also possible to render the helm chart into regular kubernetes config files and apply them yourself if you wish.

https://helm.sh/docs/helm/helm_template/

But as @jhamman says helm is going to be a straight forward way to install this on kubernetes.

**Comment by huangxinxin-szu** [comment]
> It is also possible to render the helm chart into regular kubernetes config files and apply them yourself if you wish.
> 
> https://helm.sh/docs/helm/helm_template/
> 
> But as @jhamman says helm is going to be a straight forward way to install this on kubernetes.

**Comment by xinxinh2020** [comment]
> It is also possible to render the helm chart into regular kubernetes config files and apply them yourself if you wish.
> 
> https://helm.sh/docs/helm/helm_template/
> 
> But as @jhamman says helm is going to be a straight forward way to install this on kubernetes.

Thinks for your reply.  I have deployed Pangeo via helm at first, following your advice. It is useful for me to have a general understanding about the Pange project, though it takes me serveral days to do it for some enviroment and network problem and my poor understanding for some related knowledges. I am sorry to reply so late also.

As for use case, we have a platform based on kubernetes, and user can commit their docker images and some configs(yaml format) to the platform which then schedules the user task via kubernetes. Unfortunately, our platform have not supported relm yet, so i think i have to convert the pangeo relm-chart to docker images and config files. Am I right? Any relpy and good advice would be gratefull.

**Comment by xinxinh2020** [comment]
> It is also possible to render the helm chart into regular kubernetes config files and apply them yourself if you wish.
> 
> https://helm.sh/docs/helm/helm_template/
> 
> But as @jhamman says helm is going to be a straight forward way to install this on kubernetes.

“render the helm chart into regular kubernetes config files and apply them yourself” may be what i want. I am trying this way. Thanks for your advice.

**Comment by jhamman** [comment]
Closing as this issue has lingered for some time now. Feel free to reopen if there is more to discuss here.
