### ISSUE TITLE
Automate version bumps

### ISSUE THREAD

**Issue by jhamman** [pangeo-data/helm-chart#124]
It would be really helpful if we could setup a bot to watch the two dependencies in this project (z2jh and dask-gateway) and open PRs whenever a new version is available. @jacobtomlinson has been creating some awesome github actions ([example](https://github.com/dask/helm-chart/blob/master/.github/workflows/watch-docker-hub.yml)) that do this sort of thing and I'm wondering if those can be repurposed for this use case. 

Charts to watch:
- https://jupyterhub.github.io/helm-chart/
- https://dask.org/dask-gateway-helm-repo/

Fields to replace:
https://github.com/pangeo-data/helm-chart/blob/6749ba1276f0eacc68bf23be4224504403cd2e99/pangeo/Chart.yaml#L5-L14

@jacobtomlinson - any pointers to get us started?

**Comment by jacobtomlinson** [comment]
Looks like you're doing great in your PR.

As you've spotted I haven't made an action for getting the latest version of a Helm chart yet. I am planning on doing this at some point for the RAPIDS helm chart, so you could be able to just reuse that.

**Comment by scottyhq** [comment]
@jhamman - do you think this action should just watch "stable" releases or much more frequent "development" releases https://jupyterhub.github.io/helm-chart/ ? Might want to manually bump to the current stable 0.9 and leave it there for a bit?
