### ISSUE TITLE
Incorrect value for jupyterhub.hub.services.dask-gateway.url

### ISSUE THREAD

**Issue by TomAugspurger** [pangeo-data/helm-chart#130]
https://github.com/pangeo-data/helm-chart/blob/b1a230a88d2587713eb440c9de402770f6ae32e6/pangeo/values.yaml#L43

That references `dev-staging`, which (I think) is supposed to be the namespace the chart is installed into.

**Comment by consideRatio** [comment]
It should be the name of the k8s service, which involves the namespace it seems. Like it is configured above, the pod acessing the k8s service is required to reside in the same k8s namespace also.

**Comment by jhamman** [comment]
Thanks @TomAugspurger for posting this. I think there is an open question as to whether this can be templated or if the user will always need to set this.

**Comment by TomAugspurger** [comment]
This is fixed in the `dask/daskhub` helm chart.
