### ISSUE TITLE
Fix tagged deployments

### ISSUE THREAD

**Issue by jacobtomlinson** [pangeo-data/helm-chart#2]
Currently I have the CI configured to only run `chartpress --publish-chart` on tagged commits. 

However it appears tagged commits do not have the `TRAVIS_COMMIT_RANGE` env var set which causes the [deploy to fail](https://travis-ci.org/pangeo-data/helm-chart/builds/359304806).

This needs to be fixed, but also I would be keen to have a conversation about how to want to manage releases and versioning. I'll raise a separate issue for that.

**Comment by rabernat** [comment]
Is this related to #10?

We are stuck on upgrading the pangeo.pydata.org cluster until we can get these helm charts working.

**Comment by rabernat** [comment]
So for my latest commits, travis says the following:

```
The command "chartpress --commit-range ${TRAVIS_COMMIT_RANGE}" exited with 0.
Skipping a deployment with the script provider because this is not a tagged commit
```

I think we should probably just publish every commit.

**Comment by guillaumeeb** [comment]
I don't know chartpress yet, is it still configured to publish only tagged commit? I am under the impression that every commit is published?

I think this is fine, even if at some point we would need to tag and release stable chart versions.

**Comment by jacobtomlinson** [comment]
Yes every commit it published at the moment.

**Comment by guillaumeeb** [comment]
So I think this issue can be closed. Did you open one on releases and versionning? I see #31, is this okay to discuss the problem in it?

**Comment by jacobtomlinson** [comment]
Yeah let's move this to #31
