### ISSUE TITLE
factor worker-template.yaml out of notebook docker image

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/helm-chart#32]
Currently the dask [worker template file](https://github.com/pangeo-data/helm-chart/blob/master/docker-images/notebook/worker-template.yaml) lives *inside* the notebook docker image. This makes it complicated to change the worker.

Imagine I want to spin up a new cluster in which the only difference is that the workers use a different VM with more memory. (I actually do want to do this right now.) Currently this requires a change to a single line of the worker-template.yaml file. But in order to push this change to the cluster, I have to build, tag, and push a new notebook docker image, then create a new helm chart pointing to that image, and then re-deploy the cluster

Instead, I would like to specify the `worker-template.yaml` information at the helm level. That way, to change the worker resources, I could just edit the helm chart `values.yaml` or some similar config file held by helm.

(This might also help us with auto building / tagging worker images by chartpress.)

Unfortunately, I don't understand helm nearly well enough to figure out how to make this work. So I have to cc the people who know more: @tjcrone, @yuvipanda, @choldgraf, @mrocklin.

**Comment by mrocklin** [comment]
Is there a way to use Helm to drop config files into the pod?

**Comment by mrocklin** [comment]
Alternatively, as has been suggested for notebooks we could have our container download various resources when it starts up.

**Comment by rabernat** [comment]
Is this relevant?
https://github.com/kubernetes/helm/blob/master/docs/chart_template_guide/accessing_files.md

**Comment by choldgraf** [comment]
I think this should be possible, though not exactly sure what the steps forward are. As an example, see [this PR from @minrk](https://github.com/jupyterhub/binderhub/pull/570) for BinderHub. There he exposes a new parameter in the helm chart and uses it under the hood in the BinderHub image cleaner. Perhaps that can provide some hints as to how to proceed.
