### ISSUE TITLE
move chart press page to pangeo.io

### ISSUE THREAD

**Issue by jhamman** [pangeo-data/helm-chart#35]
Currently, this helm chart is published at https://pangeo-data.github.io/helm-chart/. Can we move it to pangeo-data.org?

**Comment by jacobtomlinson** [comment]
This would be a great idea. Someone with access to the DNS of that domain needs to [create a subdomain which points to GitHub](https://help.github.com/articles/using-a-custom-domain-with-github-pages/), then we can change the settings on the repo to use the custom domain.

**Comment by jhamman** [comment]
That is @rabernat. Perhaps we should democratize the gatekeeper duties on the domain name.

**Comment by jhamman** [comment]
I've setup http://helm-chart.pangeo.io/. Once this makes it through the dns updates, this should be good to go.

**Comment by jhamman** [comment]
Update. My attempt to reroute the domain name for this site did not work. So let's leave this open until someone (maybe me) gets back to it.

**Comment by guillaumeeb** [comment]
What should be done here? Where can this be done?

**Comment by jhamman** [comment]
I honestly don't really know. I tried once and it didn't work. I also don't entirely recall what I tried. If you want to give it a go, we can set you up with credentials to make it happen.

**Comment by guillaumeeb** [comment]
I'd be happy to help here, but I honestly don't know what should be done, just DNS setting and some configuration with chartpress or directly from github here?

**Comment by consideRatio** [comment]
Hmmm I think it is typically a bit tricky to have a DNS point to something like: https://pangeo-data.github.io/helm-chart/, while it wouldn't be tricky to make it point to pangeo-data.github.io.

I suggest something like this instead: we create a CNAME record of gh.pangeo.io pointing to pangeo-data.github.io, then https://gh.pangeo.io/helm-chart will take us to https://pangeo-data.github.io/helm-chart i believe.

Hmmm... I'm not 100% about getting HTTPS certificates OK etc though, hmmm hmm... Ah nice it seems like using this CNAME solution will get us going with HTTPS directly according to [github documentation](https://github.blog/2018-05-01-github-pages-custom-domains-https/#configuring-your-domain).

**Comment by jacobtomlinson** [comment]
GitHub Pages supports exactly this. You point the DNS to GitHub and then update the project config to use the domain. GitHub handles stripping the `/helm-chart/` path. It also issues the certs for you using LetsEncrypt.

**Comment by TomAugspurger** [comment]
This won't be necessary with daskhub at https://helm.dask.org/
