### ISSUE TITLE
help wanted!

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/helm-chart#38]
This issue is just to make it explicitly clear that we are looking for people to help develop and maintain these helm charts, docker images, and related deployment instructions.

#5 (continuous deployment) remains a central goal. We would like to be able to have changes to the chart / dockerfiles automatically built and, upon merging into master, deployed in a test environment. We then want a way to automatically deploy this to pangeo.pydata.org.

We also have a long-running problem with `helm update`. We generally just have to delete and re-install the cluster in order to make it work.

It would be fantastic if someone who understands kubernetes, docker, and jupyterhub could just take this on and help us sort it out. None of the pangeo core team really has the expertise to get us out of this rut.

**Comment by mrocklin** [comment]
FWIW Helm upgrade worked for me last time around

**Comment by rabernat** [comment]
Helm update worked for me too. I updated pangeo.pydata.org tonight with the images in #42.

It feels like we are quite close to being able to automate this process. Just need to sort out some travis trickery.

**Comment by guillaumeeb** [comment]
I'm reviving some old issue here, but I'd like to revive this repo. So sorry for the noise in advance.

I think this one can be closed as this as been done in https://github.com/pangeo-data/dev.pangeo.io-deploy.

And by the way I'm volunteering for helping maintaining the helm chart.
