### ISSUE TITLE
add graphviz to notebook docker image

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/helm-chart#43]
dask experts: what is the recommended way to install graphviz? (I know it has some complicated dependencies.)

I would like to be able to visualize dask graphs from pangeo.pydata.org.

xref: https://github.com/pangeo-data/pangeo/issues/74

**Comment by rabernat** [comment]
cc @martindurant as someone who might know something about this

**Comment by mrocklin** [comment]
apt install graphviz

then

pip install graphviz

You could also try

conda install python-graphviz

but I've been generally less happy with it over the years

**Comment by ocefpaf** [comment]
> conda install python-graphviz
> but I've been generally less happy with it over the years

I'm curious to know why and if there is anything we can do to fix that.

**Comment by mrocklin** [comment]
I don't know much about the conda-forge recipe.  The defaults recipe has
been broken on-and-off for years.  I think the graphviz system library was
only compiled to support a couple image formats or something.  There was a
long github issue  on this topic at one point.  I spent a couple minutes
googling and couldn't find it though.

**Comment by martindurant** [comment]
I seem to recall that the conda package needed some PNG extras in order to be useful from dask's point of view. I definitely did this at some point and could probably find those requirements again.

**Comment by ocefpaf** [comment]
Thanks @martindurant and @mrocklin. I don't want to hijack this thread with an off-topic question so I'll be brief: if you can open issues at https://github.com/conda-forge/python-graphviz-feedstock or, even better, add a test that ensures the options you need are enabled, I can look into fixing these things.

**Comment by martindurant** [comment]
I have found that for linux, the following combination works `libiconv graphviz python-graphviz pango`

**Comment by rabernat** [comment]
@martindurant -- I'd be happy if you could add this via PR.

I would also like to add gsw to both worker and client images (https://anaconda.org/conda-forge/gsw), so if you bother to rebuild the docker images, it would be great to throw that in as well.

**Comment by rabernat** [comment]
Closed by #45
