### ISSUE TITLE
use HTTPS? 

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/helm-chart#60]
zero2jupyterhub-k8s recommends using HTTPS:
https://zero-to-jupyterhub.readthedocs.io/en/latest/security.html#https

Is there any reason we are not doing this on pangeo.pydata.org?

**Comment by jacobtomlinson** [comment]
HTTPS can be set up in a number of ways. Therefore I recommend we do not enable it by default in the helm chart, but instead include the same recommendation as z2jh in the docs.

I definitely recommend you enable it on pangeo.pydata.org. Following the instructions you shared would be the simplest way to achieve it.

But as a counter example our cluster has the lets encrypt plugin installed which means all external endpoints are HTTPS automatically. This is more useful for us as we are running multiple services on the cluster and dont want to configure HTTPS for each one individually.

**Comment by guillaumeeb** [comment]
> I recommend we do not enable it by default in the helm chart, but instead include the same recommendation as z2jh in the docs.

I think that's the way to go. And this one can be closed, as https has been activated in examples.
