### ISSUE TITLE
refactor notebook Dockerfile to use environment.yaml

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/helm-chart#61]
It would be nice to have a standalone pangeo default `pangeo_environment.yaml`. From the Dockerfile, we could then do 
```
conda install -f pangeo_environment.yaml
```

Does anyone see any problem with this approach before I try it?

**Comment by jhamman** [comment]
I think I've already done this: https://github.com/jhamman/pangeo-example-notebooks/blob/binderfy/binder/environment.yml

The binder example I've been distributing uses this and it seems to include everything we need. The one catch is that the versions are no longer pinned so a few things don't work in the examples at the moment.

**Comment by jhamman** [comment]
Closing. See https://github.com/pangeo-data/pangeo-stacks for a few pangeo environments (and docker images).
