### ISSUE TITLE
problems with compatibility with zero2jupyterhub-k8s 0.7 chart version

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/helm-chart#66]
In #63 I updated our chart to point to the latest stable release of the jupyterhub helm chart (0.7). However, when I tried to re-deploy pangeo.pydata.org with this chart, it didn't work. Specifically, the method for mounting the custom templates using extraVolumes / extraVolumeMounts didn't work, and as a result, the landing page was broken.

In https://github.com/pangeo-data/pangeo/pull/389, I pin the hub image tag to v0.6, which seems to fix the problem. In the long term, we need to fix the underlying problem.

**Comment by jacobtomlinson** [comment]
Oddly enough we just did the same upgrade and had the same problem! We are just troubleshooting it how. It looks like the path in Jupyter Hub for custom templates has changed, but there doesn't seem to be much docs on this.

**Comment by jacobtomlinson** [comment]
This has been fixed by @tam203 in pangeo-data/pangeo#390.
