### ISSUE TITLE
PV for Deploying Pangeo on the Cloud

### ISSUE THREAD

**Issue by Boes-man** [pangeo-data/helm-chart#72]
Hello, I am following the "[Deploying Pangeo on the Cloud](http://pangeo.io/setup_guides/cloud.html)" guide. I have a lab Kube cluster on AWS (not AKE). So I started from "Step Three: Configure Kubernetes". All went well. Only edited the loadBalancerIP in jupyter_config.yaml, added github oauth to secret_config.yaml

kubectl --namespace=pangeo get pod
NAME                     READY   STATUS    RESTARTS   AGE
hub-76dcc8c697-n7dp5     0/1     Pending   0          53m
proxy-7746576cb7-rzd8n   1/1     Running   0          53m

pod has unbound immediate PersistentVolumeClaims
no persistent volumes available for this claim and no storage class is set

Not sure whats required?

Thanks

**Comment by jacobtomlinson** [comment]
It sounds like your kubernetes cluster does not have volumes configured correctly. I expect you will have this issue with any pods which require volumes, not just Pangeo.

You cluster should be supplying volumes automatically using EBS on AWS. What method did you use to set up your cluster?

**Comment by Boes-man** [comment]
Hi Jacob, that is indeed the case, thanks.
