### ISSUE TITLE
Unable to mount volumes - Pangeo on the Cloud

### ISSUE THREAD

**Issue by Boes-man** [pangeo-data/helm-chart#73]
Hello, got my dynamic PV storageclass for my kube cluster lab working. Now seeing an different mount error, as per the attached.

Thanks
<img width="1125" alt="screen shot 2019-01-10 at 9 52 57 pm" src="https://user-images.githubusercontent.com/26314583/50964390-452b1200-1523-11e9-9b0f-efd2fa00d27c.png">
<img width="1353" alt="screen shot 2019-01-10 at 9 59 53 pm" src="https://user-images.githubusercontent.com/26314583/50964392-45c3a880-1523-11e9-870a-7a313b28c0ab.png">

**Comment by jacobtomlinson** [comment]
This appears to be due to a lack of `git` on the kubernetes host. As we use the `gitRepo` volume type it is required for Pangeo. 

I'm wondering if this is due to the age of your Kubernetes cluster. The `gitRepo` volume type [has been deprecated](https://kubernetes.io/docs/concepts/storage/volumes/#gitrepo) in favour of an init container performing the same function to remove the `git` dependency from Kubernetes. Therefore we should make this change in Pangeo. 

However for now as a workaround you could ensure `git` is installed on the host.

**Comment by Boes-man** [comment]
Ok I am on 1.12.3 I am off for a week but will test and let you know.

Thanks

**Comment by Boes-man** [comment]
Hey @jacobtomlinson git was already installed on all the hosts, so I updated jupyter_config.yaml and converted the volumes to emptydir and initcontainer spec. The helm deploy completes now, but I am not getting a public ip. This might be because my ingress controller is traefik?

kubectl --namespace=pangeo get svc proxy-public
NAME           TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)        AGE
proxy-public   LoadBalancer   10.100.211.118   pending     80:32638/TCP   43s

kubectl --namespace=pangeo get pod
NAME                     READY   STATUS    RESTARTS   AGE
hub-7b8bbb65f8-m6zv7     1/1     Running   0          8m25s
proxy-7746576cb7-mcpr5   1/1     Running   0          8m25s



[jupyter_config.txt](https://github.com/pangeo-data/helm-chart/files/2777760/jupyter_config.txt)

**Comment by jacobtomlinson** [comment]
Again this is likely to be due to your cluster configuration and not Pangeo. 

If you're using an ingress controller I would expect the controller to get an IP, not the hub service. Then it would use DNS entries to forward traffic internally.

**Comment by Boes-man** [comment]
OK, looks like its "up". Is there any basic/quickstart type guide so I can verify its ok?
<img width="1122" alt="screen shot 2019-01-21 at 11 11 12 pm" src="https://user-images.githubusercontent.com/26314583/51474028-20138a80-1dd2-11e9-850a-68aec70233bf.png">

**Comment by Boes-man** [comment]
what i get after clicking Start My Server
<img width="1129" alt="screen shot 2019-01-21 at 11 16 25 pm" src="https://user-images.githubusercontent.com/26314583/51474183-a16b1d00-1dd2-11e9-8c9b-41a18a8920b2.png">

**Comment by jacobtomlinson** [comment]
There are example notebooks you can run once your server is started. However it looks like you're not getting that far. Check the logs from the notebook pod to see what the issue is.

**Comment by Boes-man** [comment]
[logs-from-notebook-in-jupyter-pub-2dgit-2dtester.txt](https://github.com/pangeo-data/helm-chart/files/2781055/logs-from-notebook-in-jupyter-pub-2dgit-2dtester.txt)
Had to bump resource for the kube cluster nodes. Start My Server does launch the notebook pod but getting a different 500 error (redirect loop)...? Home page now shows Stop my server and My server. Hitting My server results in 500 error (redirect loop).

![screen shot 2019-01-22 at 12 54 58 pm](https://user-images.githubusercontent.com/26314583/51508226-7a4f3280-1e48-11e9-8940-e87958e0fdbf.png)
![screen shot 2019-01-22 at 1 17 51 pm](https://user-images.githubusercontent.com/26314583/51508236-80451380-1e48-11e9-89e1-834ad5e32413.png)
![screen shot 2019-01-22 at 1 17 59 pm](https://user-images.githubusercontent.com/26314583/51508241-863af480-1e48-11e9-9eea-afd1348d281b.png)

**Comment by Boes-man** [comment]
Also wondering whether these settings matter in the jupyter_config.yaml
`    storage:
      extraVolumes:
        - name: fuse
          hostPath:
            path: /dev/fuse
      extraVolumeMounts:
        - name: fuse
          mountPath: /dev/fuse`

**Comment by Boes-man** [comment]
Seeing javascript error in my browser console? Javascript is allowed in the browser and I have also added the site ip as specifically allowed. Both chrome and firefox have same error.

[browser_f12.txt](https://github.com/pangeo-data/helm-chart/files/2781087/browser_f12.txt)

**Comment by Boes-man** [comment]
OK, result! My ingress needed to be for proxy-public service not the hub service.
![screen shot 2019-01-22 at 3 10 43 pm](https://user-images.githubusercontent.com/26314583/51512056-12084d00-1e58-11e9-9c60-4bee0c01e739.png)

**Comment by Boes-man** [comment]
Thanks for the assistance and patience :)

**Comment by jacobtomlinson** [comment]
No problem! I'm glad you've managed to get it working. Please let us know what you're doing with it!
