### ISSUE TITLE
Permissions of Jupyterhub users on Kubernetes

### ISSUE THREAD

**Issue by zonca** [pangeo-data/helm-chart#79]
I am testing the GCE deployment from <https://github.com/pangeo-data/pangeo/blob/master/gce> on Jetstream. BTW the live demo on https://www.youtube.com/watch?v=rSOJKbfNBNk looks awesome!

I am inspecting Jupyterhub configuration, in particular:
https://github.com/pangeo-data/pangeo/blob/master/gce/jupyter-config.yaml#L62
Does this mean that each Jupyterhub user has control over Kubernetes from their pod? Could the user kill other users' pods?

**Comment by jhamman** [comment]
@jacobtomlinson - once the dust has settled on the dask-gateway integration, do you think it would be reasonable to turn off (by default) the dask-kubernetes rbac? Would this be enough to sufficiently limit the permissions of individual users on the cluster?

**Comment by jacobtomlinson** [comment]
Yes I expect that dask-gateway will completely replace dask-kubernetes here.

**Comment by jhamman** [comment]
> Yes I expect that dask-gateway will completely replace dask-kubernetes here.

@jacobtomlinson - can you advise on how we should deprecate the dask-kubernetes integration here? Does Helm have tooling for marking an option as deprecated?

**Comment by jacobtomlinson** [comment]
Not as far as I know.

I'd maybe be tempted to remove the `dask-kubernetes` python library and add a shim which raises a warning when imported telling users how to switch to Dask Gateway.

**Comment by jhamman** [comment]
closed via #133
