### ISSUE TITLE
Restricting user's resources

### ISSUE THREAD

**Issue by mrocklin** [pangeo-data/helm-chart#80]
Currently any user on our JupyterHub+Dask deployments can launch as many pods as they like.  This is troublesome because it opens us up to excessive costs and because other users can't easily get on.  What is the right way to do this?

Two approaches have come up before:

1.  Place each user in a separate namespace.  Some users, notably the UK Met office say that this is unpleasant because Pangeo is only one of many services running on their Kubernetes cluster and they'd like to have it all within a single namespace if possible.  This is probably representative of a larger concern about cleanliness polluting namespaces.
2.  Make a separate service that manages everything.  Users don't talk to Kubernetes, they talk to that thing, which talks to Kubernetes for them.  This is doable, but perhaps larger in scope than we'd like to tackle near-term.
3.  @yuvipanda mentioned that there might be user-based resource quotas in some corner of the expansive Kubernetes world.  If he has time it would be good to get links from him.

Also cc @jacobtomlinson @dsludwig

**Comment by yuvipanda** [comment]
The near-term way to do this would be:

1. One pod-priority per user / class (https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/). Maybe this is two priorities - one for user notebooks, one for user workers. This handles pre-emption
2. Use a ResourceQuota object per PriorityClass (https://kubernetes.io/docs/concepts/policy/resource-quotas/#resource-quota-per-priorityclass). This lets us restrict users' worker pods & notebook pods separately. However, this feature is only available in alpha clusters on GKE right now, but should be beta in 1.12, which is probably a month and something away.

**Comment by jacobtomlinson** [comment]
Just to add my two cents. 

- As @mrocklin said our Kubernetes cluster is used for more than just Pangeo so it would be a pain to have a namespace per user. However I remember seeing something about namespace hierarchy coming in at some point, @yuvipanda do you know anything about this?
- PodPriorities would be good. One thing I've never been sure of is whether a distrubuted dask task can cope with workers being forcibly removed mid calculation. I would like to think that the scheduler would reschedule the lost work and other workers would pick up those tasks. If this is the case each worker could be given an ever decreasing priority which would allow users to disrupt other users workers.
- Resource quotas are a thing.
- Cluster size limits in AWS are how we manage ours at the moment.

**Comment by jhamman** [comment]
Just as an update on this, we have ended up going the route of:

> Make a separate service that manages everything. Users don't talk to Kubernetes, they talk to that thing, which talks to Kubernetes for them. This is doable, but perhaps larger in scope than we'd like to tackle near-term.

This thing is dask-gateway and is now bundled as part of this chart. Resources are limited based on limits set in the dask-gateway configuration: https://gateway.dask.org/resource-limits.html

With this in mind, I'm going to close this now. We can reopen if the need arises.
