### ISSUE TITLE
upgrading to v0.8 of the JupyterHub Helm Chart

### ISSUE THREAD

**Issue by jhamman** [pangeo-data/helm-chart#82]
Jupyterhub is about to release v0.8 of the JupyterHub Helm Chart. This release has a number of improvements including optimization for autoscaling (see #58). I think we should plan to make a proper release of this chart once their release is complete. 

@jacobtomlinson - is this something you at the met office are interested in? Would you want to lead this effort?

Are there other things we should think about prior to upgrading the chart?

**Comment by jacobtomlinson** [comment]
Definitely interested in this. Happy to lead on it. 

There is usually an upgrade path as part of the release notes of z2jh (see [the one from 0.7.0](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/master/CHANGELOG.md#070---alex-blackwell---2018-09-03)). We will need to wait for that to be published before we know what we need to do.

**Comment by jhamman** [comment]
@minrk / @choldgraf - does this migration guide exist for 0.8 yet?

**Comment by choldgraf** [comment]
@jhamman check out https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/master/CHANGELOG.md#upgrading-from-07
I don't believe there's a huge amount of considerations for upgrading from .7 -> .8

**Comment by jhamman** [comment]
@jacobtomlinson, in case you missed it, v0.8 of the JupyterHub chart was posted today.
